#!/usr/bin/env bash
config_location=/etc/shadowsocks
systemd_service=shadowsocks-libev-redir
chnroute=/etc/chinadns_chnroute.txt
##########
Help(){
echo "Usage: $0 <config_name_under_$config_location> <[start]|stop>" && exit $@
}
[[ $EUID != "0" ]] && { echo "Not root user." && exit 1;}
[[ -z "$1" ]] && Help 1 || [[ "$1" == "-h" ]] || [[ "$1" == "--help" ]] && Help 0 || CONFIG=$1
[[ "$2" == "stop" ]] && unset ENABLE || ENABLE=start

if [ $ENABLE ]; then
    [[ $(systemctl is-active $systemd_service@$CONFIG.service) ]] || { echo "WARN: ss-libev is running." ;}
    domain=$(sed -n 's/[[:space:]]//;s/.*"server":"\(.*\)".*/\1/p' $config_location/$CONFIG.json 2>/dev/null)
    [[ -z "$domain" ]] && { echo "ERROR: Couldn't find your server." && exit 1;}
    port=$(sed -n 's/[[:space:]]//;s/.*"local_port":\([0-9]*\).*/\1/p' $config_location/$CONFIG.json 2>/dev/null)
    [[ -z "$port" ]] && port=1080
    echo $domain $port $ENABLE
    systemctl restart $systemd_service@$CONFIG.service
    ss-nat -s $domain -l $port -i $chnroute -u -o
else
    systemctl stop $systemd_service@$CONFIG.service
    ss-nat -f
fi
exit $?
