#!/bin/sh

set -e -o pipefail

wget -O- 'http://ftp.apnic.net/apnic/stats/apnic/delegated-apnic-latest' | \
    awk -F\| '/CN\|ipv4/ { printf("%s/%d\n", $4, 32-log($5)/log(2)) }' > \
    /tmp/chinadns_chnroute.txt

mv -f /tmp/chinadns_chnroute.txt /etc/

/root/gfwlist2dnsmasq.sh -p 5300 -o /tmp/dnsmasq_gfwlist.conf
echo 'server=/jerryxiao.cc/127.0.0.1#5300' >> /tmp/dnsmasq_gfwlist.conf
mv -f /tmp/dnsmasq_gfwlist.conf /etc/

if pidof ss-redir>/dev/null; then
    /etc/init.d/shadowsocks rules
fi

if pidof ss-redir>/dev/null; then
    /etc/init.d/dnsmasq reload
fi
