#!/bin/bash

set -e -o pipefail

wget -O- 'http://ftp.apnic.net/apnic/stats/apnic/delegated-apnic-latest' | \
    awk -F\| '/CN\|ipv4/ { printf("%s/%d\n", $4, 32-log($5)/log(2)) }' > \
    /tmp/chinadns_chnroute.txt

mkdir -p /etc/shadowsocks-libev /etc/NetworkManager/dnsmasq.d/
mv -f /tmp/chinadns_chnroute.txt /etc/shadowsocks-libev/

./gfwlist2dnsmasq.sh -p 5300 -o /tmp/dnsmasq_gfwlist.conf
echo 'server=/jerryxiao.cc/127.0.0.1#5300' >> /tmp/dnsmasq_gfwlist.conf
mv -f /tmp/dnsmasq_gfwlist.conf /etc/NetworkManager/dnsmasq.d/
